### PR TITLE
PTFE-659: migrate registry bert-e

### PR DESCRIPTION
**Pull request by Abubakarr99**
This PR migrates the download of bert-e from registry.scality.com to ghcr.io

### CODE REVIEW

**Review by gaspardmoindrot — APPROVED** [review]
LGTM, what about the file .github/workflows/release.yaml‎ ?

**Review by tcarmet — CHANGES_REQUESTED** [review]
- Rebase your branch onto the development/3.8 and retarget your PR on the `development/3.8` branch, I want at least the 3.8 release and onwards to support ghcr.
- Identify why the above was not requested in the ticket, similar scenarios can happen with devs. 
- Check your release workflow to ensure we're not uploading to registry.scality.com anymore.

**Comment by Abubakarr99** [comment]
reset

**Comment by Abubakarr99** [comment]
@tcarmet  check my comment on the ticket

**Review by tcarmet — APPROVED** [review]

**Comment by Abubakarr99** [comment]
@bert-e help

**Comment by Abubakarr99** [comment]
@bert-e reset

**Pull request merged**
